name: "Production Deployment Workflow"
run-name: ${{ github.actor }} is running the Production Deployment

# PROD USERNAME - amit-pcdy@force.com
## Push event should only work in case of feature branches
on: 
  workflow_dispatch:

  pull_request:
    branches:
      - main
      - master
    paths:
      - 'force-app/**'
    types:
      - opened
      - synchronize
      - closed

jobs: 
  build:
    name: Validate & Deploy to Salesforce Production
    uses: "./.github/workflows/template.yml"
    with:
      environment: production
      SF_INSTANCE_URL: "https://login.salesforce.com"
      SF_ALIAS: HUB_ORG
      BRANCH_NAME: main
    secrets: inherit